server:
  port: ${PORT:8080}

logging:
  level:
    org:
      atmosphere: warn

spring:
  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      client:
        registration:
          github:
            client-id:
            client-secret:
          dbApi:
            client-name:
            client-id:
            client-secret:
            client-authentication-method: basic
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/dbApi
            scope: offline_access,openid,read_accounts,read_transactions
        provider:
          dbApi:
            authorization-uri: https://simulator-api.db.com/gw/oidc/authorize
            token-uri: https://simulator-api.db.com/gw/oidc/token
            user-info-uri: https://simulator-api.db.com/gw/oidc/userinfo
            jwk-set-uri: https://simulator-api.db.com/gw/oidc/jwk
            issuer-uri: https://simulator-api.db.com/gw/oidc/
  mustache:
    check-template-location: false
# Launch the default browser when starting the application in development mode
vaadin:
  launch-browser: true
  # To improve the performance during development.
  # For more information https://vaadin.com/docs/flow/spring/tutorial-spring-configuration.html#special-configuration-parameters
  .whitelisted-packages: com.vaadin,org.vaadin,dev.hilla,com.example.application


dbApi:
  url:
    cashAccounts: https://simulator-api.db.com/gw/dbapi/banking/cashAccounts/v2
    cashAccountTransactions: https://simulator-api.db.com/gw/dbapi/banking/transactions/v2/